-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c6a804bf21979d0cae389f84c78020d1$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "tile_A_0001.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0002.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0003.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0004.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0005.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0006.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0007.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0008.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0009.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0010.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0011.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0012.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0013.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0014.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0015.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 2, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0016.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0017.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0018.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0019.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0020.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0021.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0022.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0023.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0024.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0025.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0026.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0027.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0028.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0029.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0030.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 36, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0201.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0202.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0203.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0204.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0205.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0206.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0207.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0208.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0209.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0210.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0211.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0212.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0213.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0214.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0215.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 70, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0216.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0217.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0218.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0219.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0220.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0221.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0222.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0223.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0224.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0225.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0226.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0227.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0228.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0229.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0230.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 104, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0500.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0501.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0502.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0503.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0504.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0505.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0506.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0507.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0508.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0509.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0510.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0511.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0512.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0513.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0514.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 138, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0516.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0517.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0518.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0519.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0520.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0521.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0522.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0523.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0524.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0525.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0526.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0527.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0528.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0529.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0531.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 172, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0550.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0551.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0552.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0553.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0554.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 138, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0555.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 172, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0556.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 206, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0557.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 240, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0558.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 274, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0559.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 308, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0560.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 342, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0561.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 376, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0562.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 410, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0563.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 444, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0564.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 478, y = 206, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0565.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 2, y = 240, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0566.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 36, y = 240, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0567.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 70, y = 240, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile_A_0568.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				textureRect = { x = 104, y = 240, width = 32, height = 32 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

